### ISSUE TITLE
Seeking Guidance on Using onChanged in TextFormField

### ISSUE THREAD

**Issue by piyushdevganiya** [peiffer-innovations/json_dynamic_widget#196] opened 2023-08-20 11:21 UTC
I'm currently working with Flutter's **TextFormField** widget and I'm looking to implement the **onChanged** callback effectively.

here is my code
```
{
    "type": "text_form_field",
    "id": "first_name",
    "args": {
      "initialValue": "${first_name}",
      "decoration": {
        "hintText": "John",
        "labelText": "First Name",
        "suffixIcon": {
          "type": "icon_button",
          "args": {
            "icon": {
              "type": "icon",
              "args": {
                "icon": {
                  "codePoint": 57704,
                  "fontFamily": "MaterialIcons",
                  "size": 50
                }
              }
            },
            "onPressed": "${set_value('first_name','')}"
          }
        }
      },
      "validators": [
        {
          "type": "required"
        }
      ],
      "onChanged":  <----- how to use onChanged
    }
  }
```
Thanks

**Comment by piyushdevganiya** [comment] 2023-08-21 13:37
> Hello
> 
> Here is some example [7bba92f#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15](https://github.com/peiffer-innovations/json_dynamic_widget/commit/7bba92f7d5d02fcf9042ba8ef0740cde191cedd4#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15)

i need to change first_name value on textFormField change event. how i can change that value ?

**Comment by crisperit** [comment] 2023-08-21 13:43
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/lib/src/builders/json_text_form_field_builder.dart#L437-L448

text_form_field by default is changing `first_name` variable value with the newest one

**Comment by crisperit** [comment] 2023-08-26 10:57
Closing as I suppose the issue is solved

**Closed by crisperit** 2023-08-26 10:57 UTC
