### ISSUE TITLE
Rebuilding `dropdown_button_form_field`

### ISSUE THREAD

**Issue by gredajustyna** [peiffer-innovations/json_dynamic_widget#141] opened 2023-02-15 11:26 UTC
Hello, i have a question. In my project, which uses your plugin i rebuild the widgets depending on a language, which changes with a dropdown button form field, like this:

![image](https://user-images.githubusercontent.com/83274413/219013714-17787ef2-1a8f-4ef2-ae4e-0fd519128e76.png)

Now, i want to change also selectable values of another dropdown button form field, so they would be possible to understand in a different language. The `items` are kept in the registry and i can retrieve correct ones, depending on a language (i printed it so i can see). However, the UI doesn't change. It stays the same, no matter the language, like it has not been rebuilt. The field is a child of a `set_value`, just in case. Tried to fix it with a `listen` argument, but no change. Is it possible to dynamically change the selectable items of dropdown button form field depending on a variable? Had no issues with other widgets so far.

**Comment by jpeiffer** [comment] 2023-02-23 23:47
Please provide an example that reproduces the issue.

**Comment by gredajustyna** [comment] 2023-02-28 09:30
hello, the example in the repo of this plugin: https://github.com/THCLab/oca-dart shows the issue well enough.

**Comment by crisperit** [comment] 2023-03-05 15:04
Ok - I've spotted the problem cause

@jpeiffer 
`JsonWidgetBuilder` has a logic to recreate the Widgets after the variable values has changed. 

The problem is when created by builders widgets has also a state like `JsonDropdownButtonFormFieldBuilder` 

In such a case recreating the widget is not having any effect. Instead we should set a state of already create widget..

I'll try to write a fix

**Comment by crisperit** [comment] 2023-03-05 16:14
@jpeiffer @gredajustyna 
Here it is - the fix

@jpeiffer Please check it carefully :D
https://github.com/peiffer-innovations/json_dynamic_widget/pull/147

**Comment by crisperit** [comment] 2023-03-07 06:55
The fix has been merged - so closing.

@gredajustyna Please reopen if sth still not works regarding that

**Closed by crisperit** 2023-03-07 06:55 UTC

**Comment by gredajustyna** [comment] 2023-03-07 16:13
Thank you for addressing my issue. The new fix works :)
